sonar.projectKey=personalav_spring-7-rest-mvc
sonar.organization=PersonalAV

sonar.projectName=Spring 7 REST MVC

sonar.sourceEncoding=UTF-8

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=\
**/generated/**,\
**/target/**